### ISSUE TITLE
Service instance logs plugin ignores configured skip ssl behaviour

### ISSUE THREAD

**Issue by spikymonkey** [pivotal-cf/service-instance-logs-cli-plugin#21]
The option to `--skip-ssl-validation` is set in the cf CLi on a per API basis, using `cf api`. It's then used implicitly for every interaction with that API. However, it seems that we're not making use of it in our plugin, and instead require the user to specify `--skip-ssl-validation` again:

```
➜  animal-rescue git:(gareth/s1demo) cf service-logs gateway-demo
Connected, tailing logs for service instance gateway-demo in org springone / space demo as admin...

FAILED
Error dialing trafficcontroller server: x509: certificate signed by unknown authority.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://scg-service-broker.sys.santee.cf-app.com).
Hint: try --skip-ssl-validation at your own risk.
➜  animal-rescue git:(gareth/s1demo) ✗ cf service-logs gateway-demo --skip-ssl-validation
Connected, tailing logs for service instance gateway-demo in org springone / space demo as admin...
```

This makes for a jarring experience that doesn't fit with the convention used through the rest of the CLI.

The API-level setting should be made available to the plugin via [this function](https://github.com/cloudfoundry/cli/blob/0a3ae7c2e0ca693aeb9fba589c1bf48380948b97/plugin/plugin.go#L29).

**Comment by csterwa** [comment]
@spikymonkey I am closing since we have not had any customer requests for this.
