### ISSUE TITLE
Update Application Analyzer with Feedback from Terasky

### ISSUE THREAD

**Issue by colsonrice** [pivotal-cf/service-instance-logs-cli-plugin#46]
**Background**

Terasky is requesting a few updates to the application analyzer flow

**Acceptance Criteria**

The Jenkins instructions in the mockup should include:

- Show Documentation & Plugin Links in Add Repo Instruction Accordion in Application Analyzer
-  Add a Azure Devops dropdown in repo instructions
- The Jenkins instructions in the mockup should include:
-- Link to plugin needed
-- Link to Jenkins documentation 
- Add ability to choose upgrade level in remediation flow
- Adjust upgrade wording in remediation flow
- Combine Merge pull requests & reports over time chart
 Design should be updated here: https://www.figma.com/file/uVA0FoSDtBmD9tdWNQWP8Q/Application-Analyzer?type=design&node-id=5%3A24103&mode=design&t=hnOLjes5OVvFUGEj-1

**Comment by kvmw** [comment]
@colsonrice  
wrong repo ?
